# app config
server:
  port: 8081
# mysql config
spring:
  jackson:
    time-zone: Asia/Tehran
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/auth
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      uri: mongodb://localhost:27017/authlogs
# redis config
redis:
  host: localhost
  port: 6379
  prefix: user
# jwt config
jwt:
  token:
    secret: 4A614E635266556A586E3272357538782F413F4428472B4B6250655367566B59
    validity: 600
    id:
      validity: 3600



